export const contentDB = [
  {
    title: "Title 01",
    description: "Description 01",
    category: "Category 01",
    time: "Time 01",
    date: "Date 01",
    timestamp: "Timestamp 01",
    src: "blog/images/2021/test.png",
    alt: "Alt test",
    component: "Component 01",
    link: "Link 01",
    filepath: "File 01",
  },
  {
    title: "Title 02",
    description: "Description 02",
    category: "Category 02",
    time: "Time 02",
    date: "Date 02",
    timestamp: "Timestamp 02",
    src: "blog/images/2021/test.png",
    alt: "Alt test",
    component: "Component 02",
    link: "Link 02",
    filepath: "File 02",
  },
  {
    title: "Title 03",
    description: "Description 03",
    category: "Category 03",
    time: "Time 03",
    date: "Date 03",
    timestamp: "Timestamp 03",
    src: "blog/images/2021/test.png",
    alt: "Alt test",
    component: "Component 03",
    link: "Link 03",
    filepath: "File 03",
  },
];
